/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Stats = IDL.Record({
  'totalLosses' : IDL.Float64,
  'lossCount' : IDL.Nat,
  'consecutiveLosses' : IDL.Nat,
  'totalWins' : IDL.Float64,
  'winCount' : IDL.Nat,
  'netPL' : IDL.Float64,
});
export const Trade = IDL.Record({
  'id' : IDL.Text,
  'tradeType' : IDL.Text,
  'owner' : IDL.Principal,
  'date' : IDL.Text,
  'note' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addTrade' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteTrade' : IDL.Func([IDL.Text], [], []),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getTradesByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Trade)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Stats = IDL.Record({
    'totalLosses' : IDL.Float64,
    'lossCount' : IDL.Nat,
    'consecutiveLosses' : IDL.Nat,
    'totalWins' : IDL.Float64,
    'winCount' : IDL.Nat,
    'netPL' : IDL.Float64,
  });
  const Trade = IDL.Record({
    'id' : IDL.Text,
    'tradeType' : IDL.Text,
    'owner' : IDL.Principal,
    'date' : IDL.Text,
    'note' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'addTrade' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteTrade' : IDL.Func([IDL.Text], [], []),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getTradesByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Trade)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };