/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Stats {
  'totalLosses' : number,
  'lossCount' : bigint,
  'consecutiveLosses' : bigint,
  'totalWins' : number,
  'winCount' : bigint,
  'netPL' : number,
}
export interface Trade {
  'id' : string,
  'tradeType' : string,
  'owner' : Principal,
  'date' : string,
  'note' : string,
  'timestamp' : bigint,
  'amount' : number,
}
export interface _SERVICE {
  'addTrade' : ActorMethod<[number, string, string, string], string>,
  'deleteTrade' : ActorMethod<[string], undefined>,
  'getStats' : ActorMethod<[], Stats>,
  'getTrades' : ActorMethod<[], Array<Trade>>,
  'getTradesByDateRange' : ActorMethod<[string, string], Array<Trade>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];